trigger:
  branches:
    include:
      - master

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

jobs:
- job: linux
  pool:
    vmImage: ubuntu-18.04
  steps:
    - script: './setup_linux.sh'
    - script: './build713.sh'
    - script: './deploy_linux.sh $(Build.BuildNumber)'
  displayName: 'Linux64'
