trigger:
  branches:
    include:
      - master

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

jobs:
- job: x32_ABI
  pool:
    vmImage: ubuntu-18.04
  steps:
    - script: './setup_linux.sh'
    - script: './build713_x32.sh'
    - script: './deploy_linux_x32.sh $(Build.BuildNumber)'
  displayName: 'build x32 ABI'
- job: x64_ABI
  pool:
    vmImage: ubuntu-18.04
  steps:
    - script: './setup_linux.sh'
    - script: './build713_x64.sh'
    - script: './deploy_linux_x64.sh $(Build.BuildNumber)'
  displayName: 'build x64 ABI'
